In [4]:
import array
arr = array.array('i', [i for i in range(10)])
print(arr)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [5]:
arr[5] = 100
print(arr)

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])


## numpy.array

In [6]:
import numpy as np

In [7]:
nparr = np.array([i for i in range(10)])
print(nparr)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
nparr[5] = 100

In [9]:
print(nparr)

[  0   1   2   3   4 100   6   7   8   9]


In [10]:
nparr.dtype

dtype('int64')

In [11]:
nparr[5] = 'machine learning'
print(nparr)

ValueError: invalid literal for int() with base 10: 'machine learning'

In [12]:
nparr[3] = 3.14
print(nparr)

[  0   1   2   3   4 100   6   7   8   9]


In [13]:
nparr = np.array([1, 2, 3.14])
print(nparr.dtype)

float64


In [14]:
print(nparr)

[1.   2.   3.14]


# 其他创建numpy.array方法

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.full((3, 5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [21]:
np.full((3, 5), 666.)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

In [22]:
np.full((3, 5), 666.0)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

In [23]:
np.full(shape=(3, 5), fill_value=666.0)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

# arange

In [24]:
[i for i in range(0, 10, 2)]

[0, 2, 4, 6, 8]

In [25]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [26]:
[i for i in range(0, 1, 0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [27]:
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [28]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace

In [30]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [31]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [32]:
np.random.randint(0, 10)

5

In [33]:
np.random.randint(0, 10, 10)

array([1, 8, 5, 0, 5, 3, 0, 4, 3, 1])

In [34]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
np.random.randint(4, 8, size=10)

array([4, 4, 4, 5, 4, 7, 5, 4, 5, 6])

In [36]:
np.random.randint(4, 8, size=(3, 5))

array([[7, 4, 7, 5, 7],
       [6, 7, 5, 6, 7],
       [7, 4, 5, 6, 5]])

In [37]:
np.random.seed(666)
np.random.randint(4, 8, size=10)

array([4, 6, 5, 6, 6, 6, 5, 6, 4, 5])

In [38]:
np.random.seed(666)
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [39]:
np.random.seed(666)
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [40]:
np.random.random(10)

array([0.28116849, 0.46284169, 0.23340091, 0.76706421, 0.81995656,
       0.39747625, 0.31644109, 0.15551206, 0.73460987, 0.73159555])

In [41]:
np.random.random((3, 5))

array([[0.8578588 , 0.76741234, 0.95323137, 0.29097383, 0.84778197],
       [0.3497619 , 0.92389692, 0.29489453, 0.52438061, 0.94253896],
       [0.07473949, 0.27646251, 0.4675855 , 0.31581532, 0.39016259]])

In [42]:
np.random.normal()

0.9047266176428719

In [43]:
np.random.normal(0, 1, 10)

array([-0.82628327,  0.82101369,  0.36712592,  1.65399586,  0.13946473,
       -1.21715355, -0.99494737, -1.56448586, -1.62879004,  1.23174866])

In [44]:
np.random.normal?

In [45]:
np.random?