In [1]:
import numpy as np

In [2]:
X = np.array([[1, 2, 3],
         [4, 5, 6]])

In [3]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
y = np.array([7, 8, 9])

In [5]:
X * y

array([[ 7, 16, 27],
       [28, 40, 54]])

In [6]:
X.dot(y)

array([ 50, 122])

In [11]:
X.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
y.T

array([7, 8, 9])

In [16]:
Y = np.array([[7], [8], [9]])

In [17]:
Y.dot(X)

ValueError: shapes (3,1) and (2,3) not aligned: 1 (dim 1) != 2 (dim 0)

In [18]:
X.dot(y.T)

array([ 50, 122])