In [1]:
import numpy as np

In [2]:
np.hstack([np.ones((3, 1)), np.full((3, 4), 100)])

array([[  1., 100., 100., 100., 100.],
       [  1., 100., 100., 100., 100.],
       [  1., 100., 100., 100., 100.]])

In [3]:
np.ones((3, 1))

array([[1.],
       [1.],
       [1.]])

In [4]:
np.full((3, 4), 100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [5]:
np.linspace(1, 10, 150)

array([ 1.        ,  1.06040268,  1.12080537,  1.18120805,  1.24161074,
        1.30201342,  1.36241611,  1.42281879,  1.48322148,  1.54362416,
        1.60402685,  1.66442953,  1.72483221,  1.7852349 ,  1.84563758,
        1.90604027,  1.96644295,  2.02684564,  2.08724832,  2.14765101,
        2.20805369,  2.26845638,  2.32885906,  2.38926174,  2.44966443,
        2.51006711,  2.5704698 ,  2.63087248,  2.69127517,  2.75167785,
        2.81208054,  2.87248322,  2.93288591,  2.99328859,  3.05369128,
        3.11409396,  3.17449664,  3.23489933,  3.29530201,  3.3557047 ,
        3.41610738,  3.47651007,  3.53691275,  3.59731544,  3.65771812,
        3.71812081,  3.77852349,  3.83892617,  3.89932886,  3.95973154,
        4.02013423,  4.08053691,  4.1409396 ,  4.20134228,  4.26174497,
        4.32214765,  4.38255034,  4.44295302,  4.5033557 ,  4.56375839,
        4.62416107,  4.68456376,  4.74496644,  4.80536913,  4.86577181,
        4.9261745 ,  4.98657718,  5.04697987,  5.10738255,  5.16