In [2]:
import numpy as np

In [3]:
np.hstack([np.ones((3, 1)), np.full((3, 4), 100)])

array([[  1., 100., 100., 100., 100.],
       [  1., 100., 100., 100., 100.],
       [  1., 100., 100., 100., 100.]])

In [4]:
np.ones((3, 1))

array([[1.],
       [1.],
       [1.]])

In [5]:
np.full((3, 4), 100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [6]:
np.linspace(1, 10, 150)

array([ 1.        ,  1.06040268,  1.12080537,  1.18120805,  1.24161074,
        1.30201342,  1.36241611,  1.42281879,  1.48322148,  1.54362416,
        1.60402685,  1.66442953,  1.72483221,  1.7852349 ,  1.84563758,
        1.90604027,  1.96644295,  2.02684564,  2.08724832,  2.14765101,
        2.20805369,  2.26845638,  2.32885906,  2.38926174,  2.44966443,
        2.51006711,  2.5704698 ,  2.63087248,  2.69127517,  2.75167785,
        2.81208054,  2.87248322,  2.93288591,  2.99328859,  3.05369128,
        3.11409396,  3.17449664,  3.23489933,  3.29530201,  3.3557047 ,
        3.41610738,  3.47651007,  3.53691275,  3.59731544,  3.65771812,
        3.71812081,  3.77852349,  3.83892617,  3.89932886,  3.95973154,
        4.02013423,  4.08053691,  4.1409396 ,  4.20134228,  4.26174497,
        4.32214765,  4.38255034,  4.44295302,  4.5033557 ,  4.56375839,
        4.62416107,  4.68456376,  4.74496644,  4.80536913,  4.86577181,
        4.9261745 ,  4.98657718,  5.04697987,  5.10738255,  5.16

In [11]:
np.random.normal(size=100)

array([ 5.60774569e-01,  7.29139833e-01,  1.14135774e+00, -6.62973970e-01,
       -6.98188797e-01,  1.22157855e+00, -4.21484627e-01,  8.48567124e-01,
        8.04409154e-01,  2.23074114e+00,  1.43147478e+00,  6.46778247e-02,
        4.56703973e-01, -2.14328216e-02, -3.75711336e-01,  9.73742682e-01,
       -7.20224307e-01, -9.75641353e-01, -1.18376424e-02, -1.30226564e+00,
       -7.42451689e-01,  6.12238859e-01, -1.30262533e+00,  1.04383895e+00,
        5.70879748e-01, -4.40433309e-01,  3.83338046e-01,  1.15493654e+00,
       -2.15819193e-01,  4.23960399e-01,  7.33705354e-01,  3.34244847e-01,
       -2.21676182e-02, -6.22466215e-01,  1.84185832e-01, -3.60810569e-01,
        6.52162974e-01,  5.42655812e-01, -3.08020157e-01,  1.23869417e+00,
       -1.28093637e-01,  1.32805191e+00,  1.01665487e+00, -1.27086908e+00,
        5.24377468e-01,  8.45157637e-01,  6.37624654e-01,  6.57122203e-01,
        3.90615255e-01, -7.36291758e-01, -3.04706587e-01,  3.61292425e-01,
        6.05896585e-01,  