# numpy.array 中的运算

In [1]:
n = 10
L = [i for i in range(n)]

In [2]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
%%time
n = 1000000
L = [i for i in range(n)]
A = []
for e in L:
    A.append(2*e)

Wall time: 261 ms


In [5]:
import numpy as np
A = np.arange(n)

In [6]:
A

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [7]:
L = np.arange(n)

In [8]:
%%time
A = np.array(2*e for e in L)

Wall time: 0 ns


In [9]:
A

array(<generator object <genexpr> at 0x0000029181F47830>, dtype=object)

In [10]:
%%time
2 * L

Wall time: 3 ms


array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [11]:
%%time
A = 2 * L

Wall time: 2 ms


In [12]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [13]:
n = 10
L = np.arange(n)
2*L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## universal functions

In [15]:
X = np.arange(1, 16).reshape(3, 5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [16]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [17]:
X - 1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [19]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [20]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [21]:
X // 3

array([[0, 0, 1, 1, 1],
       [2, 2, 2, 3, 3],
       [3, 4, 4, 4, 5]], dtype=int32)

In [22]:
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [23]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [24]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [25]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [26]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [27]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [28]:
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [29]:
np.power(3, X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [30]:
X


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

## 矩阵运算

In [31]:
A = np.arange(4).reshape(2, 2)

In [32]:
B = np.full((2, 2), 10)

In [33]:
A

array([[0, 1],
       [2, 3]])

In [34]:
B

array([[10, 10],
       [10, 10]])

In [35]:
A + B

array([[10, 11],
       [12, 13]])

In [36]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [37]:
A * B

array([[ 0, 10],
       [20, 30]])

In [38]:
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [39]:
A // B

array([[0, 0],
       [0, 0]], dtype=int32)

In [40]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [41]:
A

array([[0, 1],
       [2, 3]])

In [42]:
B

array([[10, 10],
       [10, 10]])

In [43]:
A.T

array([[0, 2],
       [1, 3]])

In [44]:
A

array([[0, 1],
       [2, 3]])

## 向量和矩阵的运算

In [45]:
v = np.array([1, 2])

In [46]:
A

array([[0, 1],
       [2, 3]])

In [47]:
v + A

array([[1, 3],
       [3, 5]])

In [51]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [53]:
np.vstack([v] * A.shape[0]) + A

array([[1, 3],
       [3, 5]])

In [55]:
np.tile(v, (2, 1))

array([[1, 2],
       [1, 2]])

In [56]:
np.tile(v, (2, 2))

array([[1, 2, 1, 2],
       [1, 2, 1, 2]])

In [57]:
np.tile(v, (1, 2))

array([[1, 2, 1, 2]])

In [58]:
np.tile(v, (3, 1))

array([[1, 2],
       [1, 2],
       [1, 2]])

In [59]:
np.tile(v, (2, 1)) + A

array([[1, 3],
       [3, 5]])

In [60]:
v * A

array([[0, 2],
       [2, 6]])

In [61]:
v

array([1, 2])

In [62]:
A

array([[0, 1],
       [2, 3]])

In [63]:
v.dot(A)

array([4, 7])

In [64]:
A.dot(v)

array([2, 8])

## 矩阵的逆

In [65]:
A

array([[0, 1],
       [2, 3]])

In [66]:
invA = np.linalg.inv(A)

In [67]:
invA

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [68]:
A * invA

array([[-0. ,  0.5],
       [ 2. ,  0. ]])

In [69]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [70]:
X = np.arange(16).reshape(2, 8)

In [71]:
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [72]:
np.linalg.inv(X)

LinAlgError: Last 2 dimensions of the array must be square

In [73]:
pinvX = np.linalg.pinv(X)

In [74]:
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -3.46944695e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [75]:
X.dot(pinvX)

array([[ 1.00000000e+00, -6.24500451e-17],
       [ 1.55431223e-15,  1.00000000e+00]])

In [76]:
pinvX.dot(X)

array([[ 4.16666667e-01,  3.33333333e-01,  2.50000000e-01,
         1.66666667e-01,  8.33333333e-02, -7.77156117e-16,
        -8.33333333e-02, -1.66666667e-01],
       [ 3.33333333e-01,  2.73809524e-01,  2.14285714e-01,
         1.54761905e-01,  9.52380952e-02,  3.57142857e-02,
        -2.38095238e-02, -8.33333333e-02],
       [ 2.50000000e-01,  2.14285714e-01,  1.78571429e-01,
         1.42857143e-01,  1.07142857e-01,  7.14285714e-02,
         3.57142857e-02, -4.44089210e-16],
       [ 1.66666667e-01,  1.54761905e-01,  1.42857143e-01,
         1.30952381e-01,  1.19047619e-01,  1.07142857e-01,
         9.52380952e-02,  8.33333333e-02],
       [ 8.33333333e-02,  9.52380952e-02,  1.07142857e-01,
         1.19047619e-01,  1.30952381e-01,  1.42857143e-01,
         1.54761905e-01,  1.66666667e-01],
       [-2.77555756e-17,  3.57142857e-02,  7.14285714e-02,
         1.07142857e-01,  1.42857143e-01,  1.78571429e-01,
         2.14285714e-01,  2.50000000e-01],
       [-8.33333333e-02, -2.380952

In [77]:
X.dot(pinvX)

array([[ 1.00000000e+00, -6.24500451e-17],
       [ 1.55431223e-15,  1.00000000e+00]])