# 聚合操作

In [1]:
import numpy as np
L = np.random.random(100)
L

array([0.43733298, 0.16154607, 0.93568059, 0.38091872, 0.45561795,
       0.19397084, 0.05993619, 0.38628578, 0.80133749, 0.95098523,
       0.56466473, 0.32918726, 0.24284797, 0.08211221, 0.80324503,
       0.19199457, 0.06474717, 0.34984044, 0.90856578, 0.69681375,
       0.54964402, 0.12647605, 0.44597038, 0.6876999 , 0.56321845,
       0.17763003, 0.50035164, 0.7846346 , 0.24672669, 0.54033046,
       0.39268886, 0.02030335, 0.32728452, 0.22722158, 0.22364173,
       0.00962525, 0.99758153, 0.87860988, 0.25445474, 0.39388275,
       0.72716576, 0.8614851 , 0.54246861, 0.26833744, 0.92354742,
       0.79007967, 0.27217636, 0.58125428, 0.21172675, 0.39650893,
       0.09151992, 0.30347072, 0.10748564, 0.77884137, 0.76592049,
       0.81700907, 0.62403675, 0.4774079 , 0.8500336 , 0.78188272,
       0.81408784, 0.23031249, 0.66529141, 0.19101174, 0.67059988,
       0.5360014 , 0.79425266, 0.68964227, 0.70027175, 0.00171738,
       0.96115523, 0.36715273, 0.02020173, 0.44792999, 0.15715

In [2]:
sum(L)

45.69935340835481

In [3]:
np.sum(L)

45.69935340835482

In [4]:
big_arr = np.random.random(1000000)
%timeit sum(big_arr)
%timeit np.sum(big_arr)

135 ms ± 1.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
834 µs ± 19.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
np.min(big_arr)

4.2993923454748284e-07

In [6]:
np.max(big_arr)

0.9999940365646648

In [7]:
big_arr.min()

4.2993923454748284e-07

In [8]:
big_arr.max()

0.9999940365646648

In [9]:
big_arr.sum()

500453.2177868046

In [10]:
X = np.arange(16).reshape(4, -1)

In [11]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.sum(X)

120

In [13]:
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [14]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [15]:
np.sum?

In [17]:
np.prod(X)

0

In [18]:
np.prod(X+1)

2004189184

In [19]:
np.mean(X)

7.5

In [20]:
np.median(X)

7.5

In [21]:
np.percentile?

In [22]:
np.percentile(X, q=50)

7.5

In [24]:
np.percentile(big_arr, q=50)

0.5007168050460091

In [25]:
np.median(big_arr)

0.5007168050460091

In [26]:
np.percentile(big_arr, q=100)

0.9999940365646648

In [27]:
for percent in (0, 25, 50, 75, 100):
    print(np.percentile(big_arr, q=percent))

4.2993923454748284e-07
0.25082597512279003
0.5007168050460091
0.7502727437839207
0.9999940365646648


In [28]:
np.var(big_arr)

0.0832671184797359

In [29]:
np.std(big_arr)

0.2885604243130646

In [30]:
x = np.random.normal(0, 1, size=1000000)
x

array([ 1.85382346,  0.2634905 ,  0.86583959, ..., -1.14508667,
       -0.30955249, -1.01750665])

In [32]:
np.mean(x)

-0.0017601716532388235

In [33]:
np.std(x)

1.000361682486348

## 索引

In [34]:
np.min(x)

-4.618673573042248

In [35]:
np.argmin(x)

340414

In [36]:
x[340414]

-4.618673573042248

In [37]:
np.argmax(x)

751203

In [38]:
x[751203]

4.544030419873967

In [39]:
np.max(x)

4.544030419873967

### 排序和使用索引

In [40]:
x = np.arange(20)

In [41]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [42]:
np.random.shuffle(x)

In [43]:
x

array([ 1,  8,  2, 11, 13,  4, 12,  0,  6, 15,  9, 18,  7,  3, 14,  5, 19,
       17, 10, 16])

In [44]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
x

array([ 1,  8,  2, 11, 13,  4, 12,  0,  6, 15,  9, 18,  7,  3, 14,  5, 19,
       17, 10, 16])

In [46]:
x.sort()

In [47]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
X = np.random.randint(20, size=(4, 4))

In [50]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [51]:
X

array([[ 4,  8, 12, 12],
       [ 1, 10, 17, 19],
       [ 8, 17,  2,  7],
       [13, 11, 12,  9]])

In [52]:
np.sort(X)

array([[ 4,  8, 12, 12],
       [ 1, 10, 17, 19],
       [ 2,  7,  8, 17],
       [ 9, 11, 12, 13]])

In [53]:
np.sort(X, axis=0)

array([[ 1,  8,  2,  7],
       [ 4, 10, 12,  9],
       [ 8, 11, 12, 12],
       [13, 17, 17, 19]])

In [54]:
np.sort(X, axis=1)

array([[ 4,  8, 12, 12],
       [ 1, 10, 17, 19],
       [ 2,  7,  8, 17],
       [ 9, 11, 12, 13]])

In [55]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [56]:
np.random.shuffle(x)

In [57]:
x

array([ 0, 13, 18,  8, 12,  1, 19,  2,  7, 16, 17,  6,  5,  9, 14,  4,  3,
       15, 11, 10])

In [58]:
np.argsort(x)

array([ 0,  5,  7, 16, 15, 12, 11,  8,  3, 13, 19, 18,  4,  1, 14, 17,  9,
       10,  2,  6], dtype=int64)

In [59]:
X

array([[ 4,  8, 12, 12],
       [ 1, 10, 17, 19],
       [ 8, 17,  2,  7],
       [13, 11, 12,  9]])

In [60]:
np.sort(X, axis=1)

array([[ 4,  8, 12, 12],
       [ 1, 10, 17, 19],
       [ 2,  7,  8, 17],
       [ 9, 11, 12, 13]])

In [61]:
np.argsort(X, axis=1)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [2, 3, 0, 1],
       [3, 1, 2, 0]], dtype=int64)

In [62]:
np.argsort(X, axis=0)

array([[1, 0, 2, 2],
       [0, 1, 0, 3],
       [2, 3, 3, 0],
       [3, 2, 1, 1]], dtype=int64)

In [63]:
np.partition(x, 4)

array([ 0,  1,  2,  3,  4,  5,  9,  8,  7,  6, 10, 17, 13, 19, 14, 12, 18,
       15, 11, 16])

In [64]:
np.random.shuffle(x)

In [65]:
x

array([ 3,  4, 12, 17,  5,  8, 11,  0,  1,  7, 18, 14, 13, 15, 16,  2,  6,
       19,  9, 10])

In [66]:
np.partition(x, 4)

array([ 0,  1,  2,  3,  4,  5,  6,  7, 11,  8, 18, 14, 13, 15, 16, 17, 12,
       19,  9, 10])

In [67]:
np.argpartition(x, 4)

array([ 7,  8, 15,  0,  1,  4, 16,  9,  6,  5, 10, 11, 12, 13, 14,  3,  2,
       17, 18, 19], dtype=int64)

In [68]:
X

array([[ 4,  8, 12, 12],
       [ 1, 10, 17, 19],
       [ 8, 17,  2,  7],
       [13, 11, 12,  9]])

In [70]:
np.argpartition(X, 2, axis=1)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [2, 3, 0, 1],
       [3, 1, 2, 0]], dtype=int64)

In [71]:
np.argpartition(X, 2, axis=0)

array([[1, 0, 2, 2],
       [0, 1, 0, 3],
       [2, 3, 3, 0],
       [3, 2, 1, 1]], dtype=int64)