# KNN 在scikit-learn的实现

In [1]:
raw_train_X = [[3.393533211, 2.331273381],
              [3.118573928, 1.7895812867],
              [1.345869345, 3.3643902812],
              [3.582321009, 4.6789092384],
              [2.282930235, 2.8629038929],
              [7.423192098, 4.6923098584],
              [5.745012932, 3.5389420192],
              [9.173530493, 2.5113292944],
              [7.792323530, 3.4298450302],
              [7.939824242, 0.7912324829]]
raw_train_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

In [5]:
X_train = np.array(raw_train_X)
y_train = np.array(raw_train_y)

In [28]:
x = np.array([8.092349298, 3.369841284])

In [30]:
from sklearn.neighbors import KNeighborsClassifier

In [32]:
kNN_clsfier = KNeighborsClassifier(n_neighbors=6)

In [34]:
kNN_clsfier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [36]:
X_predict = x.reshape(1, -1)

In [41]:
kNN_clsfier.predict(X_predict)

array([1])

## 重新封装KNN分类器模型

In [43]:
%run KNN/kNN.py

In [44]:
knn_cls = KNNClassifier(k=6)

In [22]:
knn_cls.fit(X_train, y_train)

KKN:k=6

In [25]:
X_predict = x.reshape(1, -1)

In [26]:
X_predict

array([[8.0923493 , 3.36984128]])

In [27]:
knn_cls.predict(X_predict)

array([1])