# 测试我们的算法

In [180]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [181]:
iris = datasets.load_iris()

In [182]:
X = iris.data

In [183]:
y = iris.target

In [184]:
X.shape

(150, 4)

In [185]:
y.shape

(150,)

## train-test-split

In [186]:
shuffle_indexes = np.random.permutation(len(X))

In [187]:
shuffle_indexes

array([ 86,  63,   2,  49,  41,  77, 106, 148,  89,  70, 143, 135,  25,
        23, 139,  60,  57,  54,  35, 123,  20,  30,  13,  71,  74,  84,
       137,  96, 128,  17,  67,  69, 118, 122,  50, 140, 127, 116, 134,
       104, 119,  12,  38, 146,   6, 105,  88,  68,  90, 108,   9,  58,
       129,  48, 107, 117,  98, 144,  22,  43,  29,  66,   0,  99, 131,
       109, 141, 120, 126,  37, 145, 101,  45, 115,  79,  76,  81,   7,
        78,  15,  19, 100, 136,  75,  97, 114,  83,  34,  53, 147, 121,
         4,  51, 111,  61,  80,  33, 133,  21, 103,  26, 149,  42,  14,
        36,  47, 102,  18, 138, 112,  72, 132, 125,  11, 124,  16, 142,
        56,  87,  93,  55,  82,  46, 110,  64,  28,  65,  44,  59,  92,
        94,   3, 113,  85,  32,  39,  95,  73,  24,  91,   5,  31,   8,
         1,  10,  40,  52,  27, 130,  62])

In [188]:
size_radio = 0.2

In [189]:
test_size = int(len(shuffle_indexes) * size_radio)

In [190]:
test_size

30

In [191]:
test_indexes = shuffle_indexes[:test_size]
trian_indexes = shuffle_indexes[test_size:]

In [192]:
test_indexes.shape

(30,)

In [193]:
trian_indexes.shape

(120,)

In [194]:
test_indexes

array([ 86,  63,   2,  49,  41,  77, 106, 148,  89,  70, 143, 135,  25,
        23, 139,  60,  57,  54,  35, 123,  20,  30,  13,  71,  74,  84,
       137,  96, 128,  17])

In [195]:
X_train = X[trian_indexes]
y_train = y[trian_indexes]
X_test= X[test_indexes]
y_test = y[test_indexes]

In [196]:
X_train.shape

(120, 4)

In [197]:
y_train.shape

(120,)

In [198]:
from PlayML.model_selection import trian_test_split

In [199]:
X_train, y_train, X_test, y_test = trian_test_split(X, y, test_radio=0.2)

In [200]:
X_train.shape

(120, 4)

In [201]:
y_train.shape

(120,)

In [202]:
X_test.shape

(30, 4)

In [203]:
y_test.shape

(30,)

In [204]:
from PlayML.kNN import KNNClassifier

In [205]:
KNNClassifier(k=3)

KKN:k=3

In [206]:
knn_cls = KNNClassifier(k=3)

In [207]:
knn_cls.fit(X_train, y_train)

KKN:k=3

In [208]:
y_predict = knn_cls.predict(X_test)

In [209]:
y_predict

array([1, 0, 2, 1, 1, 2, 2, 1, 2, 1, 1, 0, 0, 2, 2, 0, 1, 1, 0, 1, 2, 2,
       2, 0, 1, 1, 0, 2, 0, 0])

In [210]:
y_test

array([1, 0, 2, 1, 1, 2, 2, 1, 2, 1, 1, 0, 0, 2, 2, 0, 1, 1, 0, 1, 2, 2,
       2, 0, 1, 1, 0, 2, 0, 0])

In [211]:
sum(y_predict == y_test) / len(y_test)

1.0