In [1]:
import numpy as np

In [2]:
np.hstack([np.ones((3, 1)), np.full((3, 4), 100)])

array([[  1., 100., 100., 100., 100.],
       [  1., 100., 100., 100., 100.],
       [  1., 100., 100., 100., 100.]])

In [3]:
np.ones((3, 1))

array([[1.],
       [1.],
       [1.]])

In [4]:
np.full((3, 4), 100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [5]:
np.linspace(1, 10, 150)

array([ 1.        ,  1.06040268,  1.12080537,  1.18120805,  1.24161074,
        1.30201342,  1.36241611,  1.42281879,  1.48322148,  1.54362416,
        1.60402685,  1.66442953,  1.72483221,  1.7852349 ,  1.84563758,
        1.90604027,  1.96644295,  2.02684564,  2.08724832,  2.14765101,
        2.20805369,  2.26845638,  2.32885906,  2.38926174,  2.44966443,
        2.51006711,  2.5704698 ,  2.63087248,  2.69127517,  2.75167785,
        2.81208054,  2.87248322,  2.93288591,  2.99328859,  3.05369128,
        3.11409396,  3.17449664,  3.23489933,  3.29530201,  3.3557047 ,
        3.41610738,  3.47651007,  3.53691275,  3.59731544,  3.65771812,
        3.71812081,  3.77852349,  3.83892617,  3.89932886,  3.95973154,
        4.02013423,  4.08053691,  4.1409396 ,  4.20134228,  4.26174497,
        4.32214765,  4.38255034,  4.44295302,  4.5033557 ,  4.56375839,
        4.62416107,  4.68456376,  4.74496644,  4.80536913,  4.86577181,
        4.9261745 ,  4.98657718,  5.04697987,  5.10738255,  5.16

In [6]:
np.random.normal(size=100)

array([-0.26959613, -0.3462056 ,  0.12169006,  0.07860462,  2.07877214,
        2.03469876,  0.86391365,  0.11261602, -0.63949242,  0.24695549,
        0.40853193, -0.66254559,  0.47023358, -1.33475079, -0.67791015,
        1.28479805, -1.93247326, -0.59831676,  0.03763274,  2.61049442,
        0.53172419, -0.39106171,  2.17195373, -2.649499  , -1.17187299,
        0.97410562, -1.36898935, -1.52519238, -0.16389686, -0.81371864,
       -0.38002775,  0.35620028, -0.77200326,  0.99155636, -1.38975957,
       -1.0503639 , -0.36000636, -0.05059097,  0.91577313, -0.68203386,
       -1.53603467,  1.72547093,  1.49041501, -0.34288524, -0.97000283,
        0.08185236,  0.43729465,  0.43440644, -0.29186369,  0.84872328,
        1.45279262, -0.05263755, -0.38323382, -0.22416585,  0.48870838,
       -0.45695387,  0.66709548, -0.99091302, -0.91694226, -0.53432504,
        1.4285936 , -0.04654569, -1.70565792, -0.37141627, -0.87906283,
        2.00528724, -0.3238971 ,  0.45201502, -1.47618745, -0.20

In [10]:
np.random.randn(2, 3)

array([[ 0.59759999, -2.63284809,  0.13724113],
       [-0.17074377,  1.81187303, -0.25773813]])