# Numpy 多维数组基础及运算详解

## 概述

### Numpy是python数值计算非常重要的包，其他许多python科学计算的包都是以它为基础，比如： Scipy，Matplolib，Pandas等。
### 提供了高效的大数据处理能力，比python内置的list序列更少的内存占用及速度快了很多，因为Numpy是在一个连续的内存块中存储数据以及直接在整个数组上执行复杂计算。

## 多维数组

### 灵活高效的处理多维数组，多维数组对象：numpy.ndarray。ndarray对象内的元素必须是相同类型的。

## 创建多维数组ndarray对象的方法

### 1.使用array函数创建

In [1]:
import numpy as np

In [2]:
# 第一个参数可以是：可迭代对象，整数，浮点数，其他ndarray对象
res_1 = np.array([1,2,3])
print('res_1: ', res_1, type(res_1))

res_2 = np.array(range(10))
print('res_2: ', res_2, type(res_2))

res_3 = np.array(res_2)
print('res_3: ', res_3, type(res_3))

res_4 = np.array(5)
print('resn_4: ', res_4, type(res_4))

res_5 = np.array(6.8)
print('res_5: ', res_5, type(res_5))

res_1:  [1 2 3] <class 'numpy.ndarray'>
res_2:  [0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
res_3:  [0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
resn_4:  5 <class 'numpy.ndarray'>
res_5:  6.8 <class 'numpy.ndarray'>


In [3]:
# 也可以是嵌套的序列生成的多维的ndarray对象
res_1 = np.array([[1,2,3], [4,5,6]])
print(res_1)

[[1 2 3]
 [4 5 6]]


### 2.使用zeros函数创建全0数组

In [4]:
# 第一个参数可以是：指定一个长度、可迭代对象指定形状
# 形状的指定一般是2个数字组成，第一个为行数，第二个为列数，如3行2列是(3,2)
# 若是三个数字组成，第一个为最外层的维数，第二个为次外层的维数，第三个为最里面具体元素的个数。若是4个数字组成，以此类推。
res_1 = np.zeros(5)
print('res_1: ')
print(res_1)

res_2 = np.zeros((3,2))
print('res_2: ')
print(res_2)

res_3 = np.zeros((2,3,4))
print('res_3: ')
print(res_3)

res_1: 
[0. 0. 0. 0. 0.]
res_2: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]
res_3: 
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


### 3.使用ones函数创建全1的数组

### 4.使用empty函数创建没有任何意义的数组

In [5]:
# ones 和 empty用法同zeros相同
res_1 = np.ones(5)
print('res_1: ')
print(res_1)

res_2 = np.ones((3,2))
print('res_2: ')
print(res_2)

res_3 = np.ones((2,3,4))
print('res_3: ')
print(res_3)

res_4 = np.empty(5)
print('res_4: ')
print(res_4)

res_5 = np.empty((3,2))
print('res_5: ')
print(res_5)

res_6 = np.empty((2,3,4))
print('res_6: ')
print(res_6)

res_1: 
[1. 1. 1. 1. 1.]
res_2: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]
res_3: 
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
res_4: 
[1. 1. 1. 1. 1.]
res_5: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]
res_6: 
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### 5.使用arange函数直接创建连续数字的数组，跟python的range函数类似

In [6]:
res_1 = np.arange(10)
print('res_1: ')
print(res_1)

res_1: 
[0 1 2 3 4 5 6 7 8 9]


### 6.使用random函数创建一些随机数

In [7]:
# random.randn(行, 列) 创建具有正太分布的随机数组
res_1 = np.random.randn(4,3)
print(res_1)

[[-1.02325101 -1.48226891 -0.41572466]
 [-1.3249811   0.33013038 -1.18599032]
 [-0.61031148  0.18636114 -1.02426019]
 [-0.12950036 -1.54083362  0.66516575]]


In [8]:
# random.randint(最小值, 最大值, 个数) 创建随机的整数型数组
res_1 = np.random.randint(2,6,10)
print(res_1)

[4 5 2 3 5 2 3 3 2 4]


## 多维数组对象ndarray的数据类型

### 1.可通过dtype属性查看数组内元素的数据类型

In [9]:
res_1 = np.arange(10)
print('res_1: ')
print(res_1)
print(res_1.dtype)

res_1: 
[0 1 2 3 4 5 6 7 8 9]
int32


In [10]:
# 创建ndarray对象时，可以指定数据类型，只需要dtype参数设置一下
res_1 = np.array([1,2,3], dtype=np.float64)
print('res_1: ')
print(res_1)
print(res_1.dtype)

res_1: 
[1. 2. 3.]
float64


In [11]:
# 简写模式，即类型代码，float64简写为：f8 因为占8个字节
# 这段代码和上面等效
res_1 = np.array([1,2,3], dtype='f8')
print('res_1: ')
print(res_1)
print(res_1.dtype)

res_1: 
[1. 2. 3.]
float64


In [12]:
# 具体数据类型参考
# http://note.youdao.com/noteshare?id=95aed84de9dac3a734db91d986081361&sub=F6C4D4A49299403F84262303545AA98D 中的numpy 数据类型

### 2.若要改变已经创建好了的数组的数据类型，可以用ndarray对象的astype函数

In [13]:
res_1 = np.array([1,2,3], dtype='f8')
print('res_1: ')
print(res_1)
print(res_1.dtype)

res_2 = res_1.astype('u4')
print('res_2: ')
print(res_2)
print(res_2.dtype)

res_1: 
[1. 2. 3.]
float64
res_2: 
[1 2 3]
uint32


In [14]:
# 将unicode 数字类型转为整形或浮点型。必须是纯数字字符，不然会报错
res_1 = np.array(['1','2','3'])
print('res_1: ')
print(res_1)
print(res_1.dtype)

res_2 = res_1.astype('u4')
print('res_2: ')
print(res_2)
print(res_2.dtype)

res_1: 
['1' '2' '3']
<U1
res_2: 
[1 2 3]
uint32


In [15]:
# "<U1"数据类型
# <: 表示字节顺序，小端模式
# U: 表示Unicode类型
# 1: 表示元素的长度

## 多维数组的运算

### 简单运算

In [16]:
# 每个元素乘以2
res_1 = np.array([[1,2,3],[4,5,6]])
res_2 = res_1 * 2
print(res_2)

[[ 2  4  6]
 [ 8 10 12]]


In [17]:
# ndarray 对象之间的运算
res_1 = np.array([[1,2,3],[4,5,6]])
res_2 = np.array([7,8,9])
print(res_1+res_2)

[[ 8 10 12]
 [11 13 15]]


In [18]:
# 多维数组之间比较，会产生一个布尔类型的数组
res_1 = np.array([[1,2,3],[10,11,12]])
res_2 = np.array([7,8,9])
print(res_1 > res_2)

[[False False False]
 [ True  True  True]]


### 一元运算

In [19]:
res_1 = np.array([[1,2,3,4,5,6]])
print(np.sqrt(res_1))
print(np.sin(res_1))

[[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]]
[[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]]


In [20]:
# 常见一元运算参考
# http://note.youdao.com/noteshare?id=95aed84de9dac3a734db91d986081361&sub=F6C4D4A49299403F84262303545AA98D 中的一元ufunc

### 二元运算

In [21]:
res_1 = np.array([1,2,3,4,5,66])
res_2 = np.array([7,8,9,10,11,33])
print(np.maximum(res_1, res_2))
print(np.add(2,3))

[ 7  8  9 10 11 66]
5


In [22]:
# 常用的二元运算参考
# http://note.youdao.com/noteshare?id=95aed84de9dac3a734db91d986081361&sub=F6C4D4A49299403F84262303545AA98D 中的二元ufunc

### 三元运算

In [23]:
# 有时候np.where(cond,one,two) 函数可以很方便处理数组，参数：cond为条件，若数组元素级满足条件就置换为one，否则two
res_1 = np.array([-1,-2,-3,4,88])

res = np.where(res_1 < 0, 0, 999)
print(res)

[  0   0   0 999 999]


### 集合运算

In [24]:
# numpy中提供一些针对一维的集合运算，如unique函数、in1d函数等
# unique函数，跟python中的set集合类似，但unique函数的输出结果是排好序的
res_1 = np.array([5,3,6,5,4,2,1,2])
print(res_1)
print('*' * 50)

print(np.unique(res_1))

[5 3 6 5 4 2 1 2]
**************************************************
[1 2 3 4 5 6]


In [25]:
# in1d()函数返回一个布尔型数组，用于判断一个数组的元素是否有在另一个数组内
res_1 = np.array([5,3,6,5,4,2,1,2])
print(res_1)
print('*' * 50)

print(np.in1d(res_1, [5,3]))

[5 3 6 5 4 2 1 2]
**************************************************
[ True  True False  True False False False False]


In [26]:
# 其他集合运算参考
# http://note.youdao.com/noteshare?id=95aed84de9dac3a734db91d986081361&sub=F6C4D4A49299403F84262303545AA98D 中的数组的集合运算