# Numpy多维数组索引与切片详解

## 概述

### numpy中多维数组的索引与切片跟python中的列表类似，但最大的区别是，数组切片是原始数组的视图，也就是说对视图上的修改直接会影响到原始数组，因为numpy的主要是处理大数据，如果每次切片都进行一次复制，那对性能和内存是相当大的考验。

## 索引及切片

### 1.一维数组的索引及切片

In [1]:
import numpy as np

In [2]:
# 一维数组索引

res = np.array([1,2,3,4,5])
print(res[2])

3


In [3]:
# 一维数组切片
res = np.array([1,2,3,4,5])
print(res[1:3])

[2 3]


In [4]:
# 修改

# 对索引和切片的修改会直接映射到原数组。
res = np.array([1,2,3,4,5])
res[4] = 666
res[1:3] = 888
print(res)

[  1 888 888   4 666]


### 2.多维数组的索引及切片

In [5]:
# 多维数组索引

# 多维数组索引只需由外向内逐层选取

# 比如：多维数组 [[1 2 3] [4 5 6] [7 8 9]]

# 要选取6这个数字，索引为[1][2]，也可写成 [1,2]

res = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(res[1][2])
print(res[1,2])

6
6


In [6]:
# 多维数组切片

# 多维数组的切片就有所不同了，比如：

# res[:2, 1:]

# 前面的 :2 切的是行， 1: 切的是列。行是从上到下，列是从左到右

res = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(res)
print('*' * 50)
print(res[:2, 1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
**************************************************
[[2 3]
 [5 6]]


### 3.布尔型索引及切片

In [7]:
# 布尔型索引

# 布尔型索引指的是一个布尔型ndarray数组（一般为一维）对应另一个ndarray数组的每行，布尔型数组的个数要必须与另一个多维数组的行数一致。
# 若布尔型数组内的某个元素为True，则选取另一个多维数组的行，反之不选取。

# 这样说可能太抽象，下面代码说明就很好理解了。

# 下面代码是选取第一行和最后一行

res = np.random.randn(5,4)
print(res)
print('*' * 50)

res_bool = np.array([True, False, False, False, True])
print(res[res_bool])

[[-1.06011147 -0.3818709  -0.32074683  0.35618192]
 [-1.11516008 -0.81627554  0.53466137  0.24922092]
 [ 0.75305863  0.22191203  0.85009665 -0.77668319]
 [-2.2390432  -0.86258779  0.84237942 -2.12001193]
 [ 1.0819114  -0.59087549  0.28428327  0.20829699]]
**************************************************
[[-1.06011147 -0.3818709  -0.32074683  0.35618192]
 [ 1.0819114  -0.59087549  0.28428327  0.20829699]]


In [8]:
# 假设每一行代表一个字母的信息，分别是A B C D A

# 现在需要选择A字母的对应的行信息，可以看到第一行和最后一行是A字母的信息

# 通过比较操作可以生成关于字母A的布尔型数组

res = np.random.randn(5,4)
print(res)
print('*' * 50)

res_1 = np.array(['A', 'B', 'C', 'D', 'A'])
print(res[res_1 == 'A'])

[[-4.73289018e-01 -2.57268383e-03 -1.29645277e-01 -3.02841787e-01]
 [-8.82353434e-02 -2.60188905e-01  2.36838323e-01  9.55566859e-02]
 [ 7.54559663e-02 -1.98945080e+00  1.00714726e-01 -5.26640538e-01]
 [-4.94295175e-01  5.95421624e-02  3.24821842e+00  1.32946556e+00]
 [ 6.54348335e-01  1.59389762e+00  9.90335428e-01 -1.86186016e+00]]
**************************************************
[[-0.47328902 -0.00257268 -0.12964528 -0.30284179]
 [ 0.65434834  1.59389762  0.99033543 -1.86186016]]


In [9]:
# 条件索引

# 上面中默认是True的就选取，False就不选取。也可以设置条件，如：

# != 不等于

# & 与运算

# | 或运算

res = np.random.randn(5,4)
print(res)
print('*' * 50)

res_1 = np.array(['A', 'B', 'C', 'D', 'A'])
print(res[res_1 != 'A'])

[[-0.74804626 -0.91224037 -0.6652418  -0.28402599]
 [ 0.1805425   0.97433639 -0.04249194  2.8077344 ]
 [-0.88968204 -0.4330524  -0.8450193   0.87389813]
 [ 1.3793327   0.73968987 -1.38309033 -0.96609648]
 [-0.19092362  1.45079181  0.07888369 -0.83286185]]
**************************************************
[[ 0.1805425   0.97433639 -0.04249194  2.8077344 ]
 [-0.88968204 -0.4330524  -0.8450193   0.87389813]
 [ 1.3793327   0.73968987 -1.38309033 -0.96609648]]


In [10]:
res = np.random.randn(5,4)
print(res)
print('*' * 50)

res_1 = np.array(['A', 'B', 'C', 'D', 'A'])
cond1 = (res_1 == 'B') & (res_1 == 'C')
print(cond1)
print(res[cond1])
print('*' * 50)

cond2 = (res_1 == 'B') | (res_1 == 'C')
print(cond2)
print(res[cond2])

[[-0.23544925 -0.07682632 -1.42999245  2.42866694]
 [ 0.5649321  -0.09848635  0.66251763 -0.98022511]
 [ 1.09123233 -1.2901559  -0.76138614  0.07048723]
 [-0.34810342 -1.84351919  0.07232611  0.48449447]
 [-1.1652091  -2.29729621  0.72170397  0.66265002]]
**************************************************
[False False False False False]
[]
**************************************************
[False  True  True False False]
[[ 0.5649321  -0.09848635  0.66251763 -0.98022511]
 [ 1.09123233 -1.2901559  -0.76138614  0.07048723]]


In [11]:
# 由上可以看到 (zarten_1 == 'B') & (zarten_1 == 'C') ，两个布尔型数组&后全部为False，固没有选取任何的一行。

In [12]:
# 布尔型切片

# 跟多维数组的切片类似，[行, 列]第一个为行，第二个为列切片。

res = np.random.randn(5,4)
print(res)
print('*' * 50)

res_1 = np.array(['A', 'B', 'C', 'D', 'A'])
print(res[res_1 == 'A'])
print('*' * 50)
print(res[res_1 == 'A', 1:3])

[[ 1.7900851   0.8399421  -0.4869741  -0.09736918]
 [-1.54719611 -0.47067605 -0.52708923 -1.63748079]
 [ 0.90103017 -1.83914983 -0.09219735 -0.06812073]
 [-0.19992547 -1.47059949 -0.30217897  1.86446253]
 [ 0.4564606   1.68110395 -0.14696567  1.59543686]]
**************************************************
[[ 1.7900851   0.8399421  -0.4869741  -0.09736918]
 [ 0.4564606   1.68110395 -0.14696567  1.59543686]]
**************************************************
[[ 0.8399421  -0.4869741 ]
 [ 1.68110395 -0.14696567]]


### 4.花式索引

In [13]:
# 花式索引

# 花式索引跟布尔型索引类似，花式索引是可以使用整数数组进行索引，可以选取任意的行，跟布尔型索引的[True, False , False]类似，可以任意选取。花式索引更方便些。

# 注意：花式索引是传入整数数组。若为负数，将从末尾开始选取

# 例如现在选取第一行和第二行。下面将布尔型索引和花式索引做一个对比

res = np.random.randn(5,4)
print(res)
print('*' * 50)

#选取第一行和第二行

#布尔型索引做法
res_bool = np.array([True, True, False, False, False])
print(res[res_bool])
print('*' * 50)

#花式索引做法
print(res[[0, 1]])
print('*' * 50)

print(res[[0, 3]])

[[-0.11739378  0.50515451 -0.32641565 -1.1733774 ]
 [ 1.70716895  0.55896391 -0.89186106 -0.41433674]
 [ 0.17879103  0.27233262 -1.24950017 -0.38686657]
 [ 0.5643533   1.01685303  0.57092892 -0.2435751 ]
 [ 1.00079142 -0.64193677 -1.61014765  0.56000554]]
**************************************************
[[-0.11739378  0.50515451 -0.32641565 -1.1733774 ]
 [ 1.70716895  0.55896391 -0.89186106 -0.41433674]]
**************************************************
[[-0.11739378  0.50515451 -0.32641565 -1.1733774 ]
 [ 1.70716895  0.55896391 -0.89186106 -0.41433674]]
**************************************************
[[-0.11739378  0.50515451 -0.32641565 -1.1733774 ]
 [ 0.5643533   1.01685303  0.57092892 -0.2435751 ]]


In [14]:
# 花式切片

# 跟上面的类似

res = np.random.randn(5,4)
print(res)
print('*' * 50)

#选取第一行和第二行

#布尔型索引做法
res_bool = np.array([True, True, False, False, False])
print(res[res_bool])
print('*' * 50)

#花式索引做法
print(res[[0, 1], 1:3])

[[ 0.82732076 -0.20393181  1.82445509 -0.64518302]
 [-1.56129031  0.59751159  0.28627037 -0.82285692]
 [-0.59331697 -0.72280121  0.94699248  0.69392062]
 [ 1.4841157   0.29303271 -0.09814722 -0.3802427 ]
 [-1.38738494  0.63377544 -0.32051427 -1.22219868]]
**************************************************
[[ 0.82732076 -0.20393181  1.82445509 -0.64518302]
 [-1.56129031  0.59751159  0.28627037 -0.82285692]]
**************************************************
[[-0.20393181  1.82445509]
 [ 0.59751159  0.28627037]]
