# Numpy多维数组数据分析及线性代数详解

## 概述

### Numpy多维数组也可以做一些简单的数据分析，虽然数据分析处理主要是其他库，如Pandas等，但这些高级库都是以Numpy为基础的。

## 数据统计

In [2]:
# 统计二维数组所有数的平均数，求和
import numpy as np
res_1 = np.random.randn(2,2)
print(res_1)
print('*' * 50)

print(np.mean(res_1)) #平均值
print(np.sum(res_1))  #求和

[[-2.11976712 -2.04553017]
 [-1.34242519 -0.12176553]]
**************************************************
-1.4073719991317513
-5.629487996527005


In [3]:
# 也可对某行或某列的数据统计

# 方法是在函数中添加一个axis参数，0表示每列，1表示每行

res_1 = np.random.randn(3,2)
print(res_1)
print('*' * 50)

print(np.sum(res_1, axis= 0))  #每列求和
print('*' * 50)

print(np.sum(res_1, axis= 1)) #每行平均值

[[-1.08943567 -1.15580095]
 [ 0.79731509  0.12364742]
 [-1.59197288 -1.78579829]]
**************************************************
[-1.88409345 -2.81795182]
**************************************************
[-2.24523662  0.92096252 -3.37777117]


In [4]:
# 排序

# 使用函数sort

# 注意：假设原始数组为arr，若使用np.sort(arr)会创建排好序的副本，不会影响原数组；若使用arr.sort()就地排序会修改原数组

# 默认排序是在每行内排序

res_1 = np.random.randint(0,10,(3,4))
print(res_1)
print('*' * 50)

print(np.sort(res_1)) #每行排序

[[8 9 1 3]
 [1 6 0 2]
 [0 4 5 6]]
**************************************************
[[1 3 8 9]
 [0 1 2 6]
 [0 4 5 6]]


In [5]:
# 若要根据每行或每列排序，同样是使用axis参数，0表示每列，1表示每行

res_1 = np.random.randint(0,10,(3,4))
print(res_1)
print('*' * 50)

res_1.sort(axis= 0) #每列排序
print(res_1)

[[6 5 9 1]
 [8 0 7 9]
 [0 7 8 7]]
**************************************************
[[0 0 7 1]
 [6 5 8 7]
 [8 7 9 9]]


In [6]:
# 其他统计函数参考
# http://note.youdao.com/noteshare?id=95aed84de9dac3a734db91d986081361&sub=F6C4D4A49299403F84262303545AA98D 中的基本数组统计方法

## 线性代数

In [7]:
# numpy中对线性代数也有很好的支持

# 例如，计算矩阵点积使用dot()函数

# 假设两个矩阵分别为x y

# x.dot(y) 等效于 np.dot(x, y)

res_1 = np.array([[1,2], [3,4]])
print(res_1)
print('*' * 50)

res_2 = np.array([[5,6], [7,8]])
print(res_2)
print('*' * 50)

print(np.dot(res_1, res_2))

[[1 2]
 [3 4]]
**************************************************
[[5 6]
 [7 8]]
**************************************************
[[19 22]
 [43 50]]


In [8]:
# 其他一些线性代数函数参考
# http://note.youdao.com/noteshare?id=95aed84de9dac3a734db91d986081361&sub=F6C4D4A49299403F84262303545AA98D 中的常用的numpy.linalg函数