### 1. 将 NumPy 导入为 np，并查看版本

In [1]:
import numpy as np
np.__version__

'1.16.2'

### 2. 如何创建 1 维数组？
创建数字从 0 到 9 的 1 维数组。

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3. 如何创建 boolean 数组？
创建所有 True 的 3×3 NumPy 数组。

In [7]:
np.ones((3, 3), dtype=np.bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 4. 如何从 1 维数组中提取满足给定条件的项？
从 arr 中提取所有奇数。

In [14]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# arr % 2 == 1
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

### 5. 如何将 NumPy 数组中满足给定条件的项替换成另一个数值？
将 arr 中的所有奇数替换成 -1。

In [16]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### 6. 如何在不影响原始数组的前提下替换满足给定条件的项？
将 arr 中所有奇数替换成 -1，且不改变 arr。

In [18]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_c = arr.copy()
arr_c[arr % 2 == 1] = -1
arr_c
# arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### 7. 如何重塑（reshape）数组？
将 1 维数组转换成 2 维数组（两行）。

In [19]:
np.arange(10).reshape((2, -1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 8. 如何垂直堆叠两个数组？
垂直堆叠数组 a 和 b。

In [21]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
np.concatenate([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 9. 如何水平堆叠两个数组？
水平堆叠数组 a 和 b。

In [23]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [24]:
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### 10. 在不使用硬编码的前提下，如何在 NumPy 中生成自定义序列？
在不使用硬编码的前提下创建以下模式。仅使用 NumPy 函数和以下输入数组 a。

In [43]:
a = np.array([1,2,3])
b = a.reshape((3,-1))
np.hstack([np.hstack([b, b, b]).reshape((-1)), a, a, a])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [49]:
np.vstack([np.hstack([b, b, b]), a, a, a]).reshape((-1))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### 11. 如何获得两个 Python NumPy 数组中共同的项？
获取数组 a 和 b 中的共同项。

In [53]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

### 12. 如何从一个数组中移除与另一个数组重复的项？
从数组 a 中移除出现在数组 b 中的所有项。

In [61]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b)

array([1, 2, 3, 4])

### 13. 如何获取两个数组匹配元素的位置？
获取数组 a 和 b 中匹配元素的位置。

In [68]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

### 14. 如何从 NumPy 数组中提取给定范围内的所有数字？
从数组 a 中提取 5 和 10 之间的所有项。

In [73]:
a = np.arange(15)
a[(a >=5) & (a <= 10)]

array([ 5,  6,  7,  8,  9, 10])

### 15. 如何创建一个 Python 函数以对 NumPy 数组执行元素级的操作？
转换函数 maxx，使其从只能对比标量而变为对比两个数组。

In [74]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

### 16. 如何在 2d NumPy 数组中交换两个列？
在数组 arr 中交换列 1 和列 2。

In [76]:
arr = np.arange(9).reshape(3,3)
arr[:, [1, 0, 2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])