# 简介

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# 使用 NumPy 生成假数据(phony data), 总共 100 个点.
x_data = np.float32(np.random.rand(2, 100)) # 随机输入
y_data = np.dot([0.100, 0.200], x_data) + 0.300

In [3]:
x_data

array([[5.5641019e-01, 7.4735120e-02, 2.2683658e-01, 8.2411021e-01,
        5.1366287e-01, 1.9238071e-01, 4.2304912e-01, 6.0708153e-01,
        1.2043954e-01, 3.9679864e-01, 7.1536995e-02, 1.9214402e-01,
        2.7034653e-04, 3.5547733e-01, 2.8387028e-01, 1.5161462e-01,
        2.9886317e-01, 9.3162048e-01, 9.6724349e-01, 4.1472331e-01,
        2.3856276e-01, 8.3401823e-01, 4.9405721e-01, 6.4619237e-01,
        8.1558520e-01, 7.2384542e-01, 6.8918502e-01, 5.2613395e-01,
        8.7672246e-01, 7.5991648e-01, 3.8965353e-01, 9.6293861e-01,
        2.5612634e-01, 2.1436197e-01, 9.9445838e-01, 8.1241488e-01,
        6.1984551e-01, 8.7503493e-01, 2.0841290e-01, 1.9208512e-01,
        1.8229274e-01, 3.0200246e-01, 8.9647716e-01, 5.7912236e-01,
        8.3621323e-01, 6.1529428e-01, 2.2450401e-01, 3.0488381e-01,
        8.0223538e-02, 1.4218193e-01, 8.3865100e-01, 2.4439816e-01,
        4.5893866e-01, 1.1517289e-01, 1.3332388e-01, 7.6077259e-01,
        2.3345360e-01, 4.2041373e-02, 3.7023389e

In [4]:
y_data

array([0.54415345, 0.38963184, 0.3649576 , 0.51800603, 0.52046742,
       0.38189751, 0.51854797, 0.54036256, 0.35059571, 0.39044707,
       0.47198655, 0.34298893, 0.46434705, 0.44288193, 0.44442236,
       0.50325408, 0.40646524, 0.41231285, 0.53172303, 0.49243442,
       0.42039616, 0.40151972, 0.49399053, 0.42592951, 0.56996824,
       0.41842921, 0.56279565, 0.46375603, 0.5817417 , 0.4776284 ,
       0.44843025, 0.46253509, 0.37214496, 0.32624109, 0.46972045,
       0.4500051 , 0.49541856, 0.58434201, 0.37103794, 0.38382382,
       0.51544611, 0.51270205, 0.43842823, 0.50361046, 0.45548489,
       0.48626494, 0.49954816, 0.41926754, 0.47138364, 0.33191583,
       0.54600199, 0.37573777, 0.40677045, 0.46768748, 0.47523373,
       0.5751343 , 0.40176129, 0.45374182, 0.50706275, 0.48343164,
       0.56306696, 0.43876406, 0.42255341, 0.36037993, 0.45512232,
       0.50617207, 0.39771075, 0.5312233 , 0.48650499, 0.4094651 ,
       0.54410459, 0.48172022, 0.32561233, 0.55909854, 0.32539

In [5]:
np.random.rand(2, 100)

array([[0.87640202, 0.14773207, 0.52741952, 0.16507117, 0.86276428,
        0.40751489, 0.37117598, 0.47172785, 0.63773182, 0.3920297 ,
        0.81293234, 0.56877405, 0.25429524, 0.8907436 , 0.31608282,
        0.6633145 , 0.48129529, 0.02238748, 0.44245312, 0.62087217,
        0.50366019, 0.42084792, 0.47093432, 0.93726335, 0.56362234,
        0.02178072, 0.40232644, 0.6652799 , 0.59509097, 0.48682506,
        0.074604  , 0.97214761, 0.41508254, 0.78466759, 0.96266065,
        0.61874671, 0.2819804 , 0.15027773, 0.245699  , 0.49086373,
        0.52786813, 0.21190668, 0.80773106, 0.81244959, 0.20130258,
        0.6622612 , 0.88361155, 0.45644846, 0.73697785, 0.47153262,
        0.76519392, 0.13029004, 0.99542288, 0.15008034, 0.7911828 ,
        0.41975381, 0.09571078, 0.77001509, 0.80641146, 0.0863667 ,
        0.85438028, 0.25665429, 0.64610204, 0.01067569, 0.13320566,
        0.09533776, 0.1806567 , 0.39247913, 0.26226884, 0.93014803,
        0.01791453, 0.02174143, 0.55854717, 0.59

In [6]:
# 构造一个线性模型
# 
b = tf.Variable(tf.zeros([1]))
W = tf.Variable(tf.random_uniform([1, 2], -1.0, 1.0))
y = tf.matmul(W, x_data) + b

Instructions for updating:
Colocations handled automatically by placer.


In [7]:
# 最小化方差
loss = tf.reduce_mean(tf.square(y - y_data))
optimizer = tf.train.GradientDescentOptimizer(0.5)
train = optimizer.minimize(loss)

In [8]:
# 初始化变量
init = tf.global_variables_initializer()

In [9]:
# 启动图 (graph)
sess = tf.Session()
sess.run(init)

In [10]:
# 拟合平面
for step in range(0, 201):
    sess.run(train)
    if step % 20 == 0:
        print(step, sess.run(W), sess.run(b))

0 [[-0.1740371  -0.00807869]] [1.3782291]
20 [[-0.05022167  0.04142149]] [0.46913117]
40 [[0.05700692 0.15106878]] [0.35041213]
60 [[0.08745337 0.18514408]] [0.31503832]
80 [[0.09629916 0.19552612]] [0.30448788]
100 [[0.0989021  0.19865827]] [0.3013396]
120 [[0.09967329 0.19959845]] [0.30039993]
140 [[0.09990261 0.19987994]] [0.3001194]
160 [[0.09997095 0.19996415]] [0.30003566]
180 [[0.09999132 0.19998929]] [0.30001065]
200 [[0.09999741 0.1999968 ]] [0.30000317]
